# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intellistock\ui\ui_mainwindow.ui'
#
# Created: Thu Dec  4 12:54:16 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(641, 480)
        MainWindow.setWindowTitle(_fromUtf8("Stock"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.navigationLayout = QtGui.QVBoxLayout()
        self.navigationLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.navigationLayout.setObjectName(_fromUtf8("navigationLayout"))
        self.lineEdit_search = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_search.setObjectName(_fromUtf8("lineEdit_search"))
        self.navigationLayout.addWidget(self.lineEdit_search)
        self.listWidget_stocks = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_stocks.sizePolicy().hasHeightForWidth())
        self.listWidget_stocks.setSizePolicy(sizePolicy)
        self.listWidget_stocks.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_stocks.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_stocks.setObjectName(_fromUtf8("listWidget_stocks"))
        self.navigationLayout.addWidget(self.listWidget_stocks)
        self.progressBar_load = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_load.sizePolicy().hasHeightForWidth())
        self.progressBar_load.setSizePolicy(sizePolicy)
        self.progressBar_load.setMinimumSize(QtCore.QSize(120, 0))
        self.progressBar_load.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar_load.setVisible(False)
        self.progressBar_load.setTextVisible(False)
        self.progressBar_load.setObjectName(_fromUtf8("progressBar_load"))
        self.navigationLayout.addWidget(self.progressBar_load)
        self.horizontalLayout.addLayout(self.navigationLayout)
        self.contentLayout = QtGui.QVBoxLayout()
        self.contentLayout.setObjectName(_fromUtf8("contentLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.contentLayout.addWidget(self.tabWidget)
        self.groupBox_view = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_view.setObjectName(_fromUtf8("groupBox_view"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_view)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_zoom = QtGui.QLabel(self.groupBox_view)
        self.label_zoom.setObjectName(_fromUtf8("label_zoom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_zoom)
        self.slider_zoom = QtGui.QSlider(self.groupBox_view)
        self.slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.slider_zoom.setObjectName(_fromUtf8("slider_zoom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.slider_zoom)
        self.label_time = QtGui.QLabel(self.groupBox_view)
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_time)
        self.slider_time = QtGui.QSlider(self.groupBox_view)
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName(_fromUtf8("slider_time"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.slider_time)
        self.contentLayout.addWidget(self.groupBox_view)
        self.horizontalLayout.addLayout(self.contentLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName(_fromUtf8("menuStock"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_aboutStock = QtGui.QAction(MainWindow)
        self.action_aboutStock.setObjectName(_fromUtf8("action_aboutStock"))
        self.action_showToolbar = QtGui.QAction(MainWindow)
        self.action_showToolbar.setCheckable(True)
        self.action_showToolbar.setChecked(True)
        self.action_showToolbar.setObjectName(_fromUtf8("action_showToolbar"))
        self.action_showStatusbar = QtGui.QAction(MainWindow)
        self.action_showStatusbar.setCheckable(True)
        self.action_showStatusbar.setChecked(True)
        self.action_showStatusbar.setObjectName(_fromUtf8("action_showStatusbar"))
        self.action_fullscreen = QtGui.QAction(MainWindow)
        self.action_fullscreen.setObjectName(_fromUtf8("action_fullscreen"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_menubar = QtGui.QAction(MainWindow)
        self.action_menubar.setCheckable(True)
        self.action_menubar.setChecked(True)
        self.action_menubar.setObjectName(_fromUtf8("action_menubar"))
        self.action_favorite = QtGui.QAction(MainWindow)
        self.action_favorite.setEnabled(False)
        self.action_favorite.setObjectName(_fromUtf8("action_favorite"))
        self.action_simulation = QtGui.QAction(MainWindow)
        self.action_simulation.setEnabled(False)
        self.action_simulation.setObjectName(_fromUtf8("action_simulation"))
        self.menuStock.addAction(self.action_simulation)
        self.menuStock.addAction(self.action_exit)
        self.menuView.addAction(self.action_showToolbar)
        self.menuView.addAction(self.action_showStatusbar)
        self.menuView.addAction(self.action_fullscreen)
        self.menuTools.addAction(self.action_favorite)
        self.menuHelp.addAction(self.action_aboutStock)
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.action_showStatusbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.statusbar.setVisible)
        QtCore.QObject.connect(self.action_showToolbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.toolBar.setVisible)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "gyorskeresés", None))
        self.groupBox_view.setTitle(_translate("MainWindow", "Nézet", None))
        self.label_zoom.setText(_translate("MainWindow", "Nagyítás", None))
        self.label_time.setText(_translate("MainWindow", "Idő", None))
        self.menuStock.setTitle(_translate("MainWindow", "&Stock", None))
        self.menuView.setTitle(_translate("MainWindow", "&Nézet", None))
        self.menuTools.setTitle(_translate("MainWindow", "&Eszközök", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Súg&ó", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Eszköztár", None))
        self.action_aboutStock.setText(_translate("MainWindow", "A &Stock névjegye", None))
        self.action_showToolbar.setText(_translate("MainWindow", "&Eszköztár", None))
        self.action_showToolbar.setStatusTip(_translate("MainWindow", "Eszköztár megjelenítése/eltejtése.", None))
        self.action_showToolbar.setShortcut(_translate("MainWindow", "Ctrl+E, T", None))
        self.action_showStatusbar.setText(_translate("MainWindow", "&Állapotsor", None))
        self.action_showStatusbar.setStatusTip(_translate("MainWindow", "Állapotsáv megjelenítése/elrejtése.", None))
        self.action_showStatusbar.setShortcut(_translate("MainWindow", "Ctrl+E, S", None))
        self.action_fullscreen.setText(_translate("MainWindow", "&Teljes képernyő", None))
        self.action_fullscreen.setStatusTip(_translate("MainWindow", "Ablak teljes képernyőre váltása.", None))
        self.action_fullscreen.setShortcut(_translate("MainWindow", "F11", None))
        self.action_exit.setText(_translate("MainWindow", "&Kilépés", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_menubar.setText(_translate("MainWindow", "Menüsor", None))
        self.action_menubar.setShortcut(_translate("MainWindow", "Ctrl+E, M", None))
        self.action_favorite.setText(_translate("MainWindow", "&Kedvenc", None))
        self.action_favorite.setStatusTip(_translate("MainWindow", "Kijelölt részvény hozzáadása/eltávolitása a kedvencek közül.", None))
        self.action_favorite.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.action_simulation.setText(_translate("MainWindow", "Szimuláció", None))

