# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Fri Jan  9 22:43:31 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(683, 493)
        MainWindow.setWindowTitle(_fromUtf8("Stock"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.navigationLayout = QtGui.QVBoxLayout()
        self.navigationLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.navigationLayout.setObjectName(_fromUtf8("navigationLayout"))
        self.lineEdit_search = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_search.setObjectName(_fromUtf8("lineEdit_search"))
        self.navigationLayout.addWidget(self.lineEdit_search)
        self.listWidget_stocks = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_stocks.sizePolicy().hasHeightForWidth())
        self.listWidget_stocks.setSizePolicy(sizePolicy)
        self.listWidget_stocks.setMinimumSize(QtCore.QSize(120, 0))
        self.listWidget_stocks.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget_stocks.setObjectName(_fromUtf8("listWidget_stocks"))
        self.navigationLayout.addWidget(self.listWidget_stocks)
        self.progressBar_load = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_load.sizePolicy().hasHeightForWidth())
        self.progressBar_load.setSizePolicy(sizePolicy)
        self.progressBar_load.setMinimumSize(QtCore.QSize(120, 0))
        self.progressBar_load.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar_load.setVisible(False)
        self.progressBar_load.setTextVisible(False)
        self.progressBar_load.setObjectName(_fromUtf8("progressBar_load"))
        self.navigationLayout.addWidget(self.progressBar_load)
        self.horizontalLayout.addLayout(self.navigationLayout)
        self.contentLayout = QtGui.QVBoxLayout()
        self.contentLayout.setObjectName(_fromUtf8("contentLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.contentLayout.addWidget(self.tabWidget)
        self.groupBox_time = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_time.setObjectName(_fromUtf8("groupBox_time"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_time)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_near_past = QtGui.QLabel(self.groupBox_time)
        self.label_near_past.setObjectName(_fromUtf8("label_near_past"))
        self.gridLayout.addWidget(self.label_near_past, 0, 0, 1, 1)
        self.slider_near_future = QtGui.QSlider(self.groupBox_time)
        self.slider_near_future.setMinimum(0)
        self.slider_near_future.setMaximum(72)
        self.slider_near_future.setProperty("value", 24)
        self.slider_near_future.setOrientation(QtCore.Qt.Horizontal)
        self.slider_near_future.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_near_future.setTickInterval(24)
        self.slider_near_future.setObjectName(_fromUtf8("slider_near_future"))
        self.gridLayout.addWidget(self.slider_near_future, 2, 1, 1, 1)
        self.label_far_past_2 = QtGui.QLabel(self.groupBox_time)
        self.label_far_past_2.setObjectName(_fromUtf8("label_far_past_2"))
        self.gridLayout.addWidget(self.label_far_past_2, 3, 0, 1, 1)
        self.slider_far_past = QtGui.QSlider(self.groupBox_time)
        self.slider_far_past.setMinimum(0)
        self.slider_far_past.setMaximum(90)
        self.slider_far_past.setProperty("value", 15)
        self.slider_far_past.setOrientation(QtCore.Qt.Horizontal)
        self.slider_far_past.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_far_past.setTickInterval(15)
        self.slider_far_past.setObjectName(_fromUtf8("slider_far_past"))
        self.gridLayout.addWidget(self.slider_far_past, 1, 1, 1, 1)
        self.slider_far_future = QtGui.QSlider(self.groupBox_time)
        self.slider_far_future.setMinimum(0)
        self.slider_far_future.setMaximum(90)
        self.slider_far_future.setProperty("value", 15)
        self.slider_far_future.setSliderPosition(15)
        self.slider_far_future.setTracking(True)
        self.slider_far_future.setOrientation(QtCore.Qt.Horizontal)
        self.slider_far_future.setInvertedAppearance(False)
        self.slider_far_future.setInvertedControls(True)
        self.slider_far_future.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_far_future.setTickInterval(15)
        self.slider_far_future.setObjectName(_fromUtf8("slider_far_future"))
        self.gridLayout.addWidget(self.slider_far_future, 3, 1, 1, 1)
        self.label_far_past = QtGui.QLabel(self.groupBox_time)
        self.label_far_past.setObjectName(_fromUtf8("label_far_past"))
        self.gridLayout.addWidget(self.label_far_past, 1, 0, 1, 1)
        self.label_near_future = QtGui.QLabel(self.groupBox_time)
        self.label_near_future.setObjectName(_fromUtf8("label_near_future"))
        self.gridLayout.addWidget(self.label_near_future, 2, 0, 1, 1)
        self.spin_near_past = QtGui.QSpinBox(self.groupBox_time)
        self.spin_near_past.setObjectName(_fromUtf8("spin_near_past"))
        self.gridLayout.addWidget(self.spin_near_past, 0, 2, 1, 1)
        self.spin_far_past = QtGui.QSpinBox(self.groupBox_time)
        self.spin_far_past.setObjectName(_fromUtf8("spin_far_past"))
        self.gridLayout.addWidget(self.spin_far_past, 1, 2, 1, 1)
        self.slider_near_past = QtGui.QSlider(self.groupBox_time)
        self.slider_near_past.setMinimum(0)
        self.slider_near_past.setMaximum(240)
        self.slider_near_past.setSingleStep(1)
        self.slider_near_past.setProperty("value", 24)
        self.slider_near_past.setOrientation(QtCore.Qt.Horizontal)
        self.slider_near_past.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_near_past.setTickInterval(24)
        self.slider_near_past.setObjectName(_fromUtf8("slider_near_past"))
        self.gridLayout.addWidget(self.slider_near_past, 0, 1, 1, 1)
        self.spin_near_future = QtGui.QSpinBox(self.groupBox_time)
        self.spin_near_future.setObjectName(_fromUtf8("spin_near_future"))
        self.gridLayout.addWidget(self.spin_near_future, 2, 2, 1, 1)
        self.spin_far_future = QtGui.QSpinBox(self.groupBox_time)
        self.spin_far_future.setObjectName(_fromUtf8("spin_far_future"))
        self.gridLayout.addWidget(self.spin_far_future, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_default_params = QtGui.QPushButton(self.groupBox_time)
        self.btn_default_params.setDefault(False)
        self.btn_default_params.setFlat(False)
        self.btn_default_params.setObjectName(_fromUtf8("btn_default_params"))
        self.horizontalLayout_2.addWidget(self.btn_default_params)
        self.btn_update_all = QtGui.QPushButton(self.groupBox_time)
        self.btn_update_all.setEnabled(True)
        self.btn_update_all.setMouseTracking(False)
        self.btn_update_all.setObjectName(_fromUtf8("btn_update_all"))
        self.horizontalLayout_2.addWidget(self.btn_update_all)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 3)
        self.contentLayout.addWidget(self.groupBox_time)
        self.horizontalLayout.addLayout(self.contentLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName(_fromUtf8("menuStock"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_aboutStock = QtGui.QAction(MainWindow)
        self.action_aboutStock.setObjectName(_fromUtf8("action_aboutStock"))
        self.action_showToolbar = QtGui.QAction(MainWindow)
        self.action_showToolbar.setCheckable(True)
        self.action_showToolbar.setChecked(True)
        self.action_showToolbar.setObjectName(_fromUtf8("action_showToolbar"))
        self.action_showStatusbar = QtGui.QAction(MainWindow)
        self.action_showStatusbar.setCheckable(True)
        self.action_showStatusbar.setChecked(True)
        self.action_showStatusbar.setObjectName(_fromUtf8("action_showStatusbar"))
        self.action_fullscreen = QtGui.QAction(MainWindow)
        self.action_fullscreen.setObjectName(_fromUtf8("action_fullscreen"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_menubar = QtGui.QAction(MainWindow)
        self.action_menubar.setCheckable(True)
        self.action_menubar.setChecked(True)
        self.action_menubar.setObjectName(_fromUtf8("action_menubar"))
        self.action_favorite = QtGui.QAction(MainWindow)
        self.action_favorite.setEnabled(False)
        self.action_favorite.setObjectName(_fromUtf8("action_favorite"))
        self.action_simulation = QtGui.QAction(MainWindow)
        self.action_simulation.setEnabled(False)
        self.action_simulation.setObjectName(_fromUtf8("action_simulation"))
        self.menuStock.addAction(self.action_simulation)
        self.menuStock.addAction(self.action_exit)
        self.menuView.addAction(self.action_showToolbar)
        self.menuView.addAction(self.action_showStatusbar)
        self.menuView.addAction(self.action_fullscreen)
        self.menuTools.addAction(self.action_favorite)
        self.menuHelp.addAction(self.action_aboutStock)
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.action_showStatusbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.statusbar.setVisible)
        QtCore.QObject.connect(self.action_showToolbar, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.toolBar.setVisible)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.slider_near_past, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spin_near_past.setValue)
        QtCore.QObject.connect(self.spin_near_past, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_near_past.setValue)
        QtCore.QObject.connect(self.slider_far_past, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spin_far_past.setValue)
        QtCore.QObject.connect(self.spin_far_past, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_far_past.setValue)
        QtCore.QObject.connect(self.slider_near_future, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spin_near_future.setValue)
        QtCore.QObject.connect(self.spin_near_future, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_near_future.setValue)
        QtCore.QObject.connect(self.slider_far_future, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spin_far_future.setValue)
        QtCore.QObject.connect(self.spin_far_future, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slider_far_future.setValue)
        QtCore.QObject.connect(self.slider_near_past, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spin_near_past.setValue)
        QtCore.QObject.connect(self.slider_far_past, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spin_far_past.setValue)
        QtCore.QObject.connect(self.slider_near_future, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spin_near_future.setValue)
        QtCore.QObject.connect(self.slider_far_future, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spin_far_future.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "gyorskeresés", None))
        self.groupBox_time.setTitle(_translate("MainWindow", "Predikciós időparaméterek", None))
        self.label_near_past.setText(_translate("MainWindow", "Predikciós közelmúlt [óra]", None))
        self.label_far_past_2.setText(_translate("MainWindow", "Predikálandó távoljövő [nap]", None))
        self.label_far_past.setText(_translate("MainWindow", "Predikciós távolmúlt [nap]", None))
        self.label_near_future.setText(_translate("MainWindow", "Predikálandó közeljövő [óra]", None))
        self.btn_default_params.setText(_translate("MainWindow", "Alapértelmezett", None))
        self.btn_update_all.setText(_translate("MainWindow", "Frissítés", None))
        self.menuStock.setTitle(_translate("MainWindow", "&Stock", None))
        self.menuView.setTitle(_translate("MainWindow", "&Nézet", None))
        self.menuTools.setTitle(_translate("MainWindow", "&Eszközök", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Súg&ó", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Eszköztár", None))
        self.action_aboutStock.setText(_translate("MainWindow", "A &Stock névjegye", None))
        self.action_showToolbar.setText(_translate("MainWindow", "&Eszköztár", None))
        self.action_showToolbar.setStatusTip(_translate("MainWindow", "Eszköztár megjelenítése/eltejtése.", None))
        self.action_showToolbar.setShortcut(_translate("MainWindow", "Ctrl+E, T", None))
        self.action_showStatusbar.setText(_translate("MainWindow", "&Állapotsor", None))
        self.action_showStatusbar.setStatusTip(_translate("MainWindow", "Állapotsáv megjelenítése/elrejtése.", None))
        self.action_showStatusbar.setShortcut(_translate("MainWindow", "Ctrl+E, S", None))
        self.action_fullscreen.setText(_translate("MainWindow", "&Teljes képernyő", None))
        self.action_fullscreen.setStatusTip(_translate("MainWindow", "Ablak teljes képernyőre váltása.", None))
        self.action_fullscreen.setShortcut(_translate("MainWindow", "F11", None))
        self.action_exit.setText(_translate("MainWindow", "&Kilépés", None))
        self.action_exit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_menubar.setText(_translate("MainWindow", "Menüsor", None))
        self.action_menubar.setShortcut(_translate("MainWindow", "Ctrl+E, M", None))
        self.action_favorite.setText(_translate("MainWindow", "&Kedvenc", None))
        self.action_favorite.setStatusTip(_translate("MainWindow", "Kijelölt részvény hozzáadása/eltávolitása a kedvencek közül.", None))
        self.action_favorite.setShortcut(_translate("MainWindow", "Ctrl+F", None))
        self.action_simulation.setText(_translate("MainWindow", "Szimuláció", None))

